FINVIZ_CONFIG = {
    "enabled": True,
    "base_url": "https://elite.finviz.com/export",
    "screener_base_url": "https://elite.finviz.com/export/screener",
    "stock_daily_base_url": "https://elite.finviz.com/export/stock",
    "default_filters": "geo_usa",
    "view": "152",
    "filter_type": "4",
    "timeout": 20,
    "cache_minutes": 60,
}

FINVIZ_DECISION_COLUMNS = [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    24,
    25,
    26,
    27,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
]
FINVIZ_DECISION_COLUMNS_STRING = ",".join(str(column) for column in FINVIZ_DECISION_COLUMNS)
FINVIZ_DISCOVERY_COLUMNS_STRING = ",".join(str(column) for column in range(111))

FINVIZ_COLUMNS = {
    "no": 0,
    "ticker": 1,
    "company": 2,
    "sector": 3,
    "industry": 4,
    "country": 5,
    "market_cap": 6,
    "pe": 7,
    "forward_pe": 8,
    "peg": 9,
    "ps": 10,
    "pb": 11,
    "pc": 12,
    "pfcf": 13,
    "shares_outstanding": 25,
    "shares_float": 26,
    "float_outstanding_pct": 27,
    "short_float": 31,
    "short_ratio": 32,
    "roa": 33,
    "roe": 34,
    "roi": 35,
    "current_ratio": 36,
    "quick_ratio": 37,
    "lt_debt_to_equity": 38,
    "debt_to_equity": 39,
    "gross_margin": 40,
    "operating_margin": 41,
    "profit_margin": 42,
    "beta": 49,
    "atr": 50,
    "volatility_week": 51,
    "volatility_month": 52,
    "sma20": 53,
    "sma50": 54,
    "sma200": 55,
    "high_52w": 58,
    "low_52w": 59,
    "rsi": 60,
    "gap": 61,
    "average_volume": 63,
    "relative_volume": 64,
    "price": 65,
    "change": 66,
    "volume": 67,
    "earnings_date": 68,
}

SEC_CONFIG = {
    "enabled": True,
    "ticker_cik_url": "https://www.sec.gov/files/company_tickers.json",
    "submissions_base_url": "https://data.sec.gov/submissions",
    "companyfacts_base_url": "https://data.sec.gov/api/xbrl/companyfacts",
    "timeout": 20,
    "cache_dir": ".cache/sec",
    "cik_map_ttl_seconds": 60 * 60 * 24,
    "submissions_ttl_seconds": 60 * 60 * 6,
    "companyfacts_ttl_seconds": 60 * 60 * 6,
    "filing_text_ttl_seconds": 60 * 60 * 24 * 30,
}
SEC_CONFIG["base_url"] = "https://data.sec.gov"
SEC_CONFIG["cache_minutes"] = SEC_CONFIG["submissions_ttl_seconds"] // 60

YFINANCE_CONFIG = {
    "enabled": True,
    "default_period": "5y",
    "short_period": "1y",
    "interval": "1d",
    "timeout": 20,
}

DCF_DEFAULTS = {
    "forecast_years": 5,
    "wacc": 0.095,
    "terminal_growth": 0.025,
    "terminal_multiple": 15.0,
    "tax_rate": 0.21,
    "margin_of_safety": 0.30,
}

DEBUG_MODE = False

CLAUSE_ENGINE_CONFIG = {
    "enabled": True,
    "max_clause_chars": 1800,
    "min_clause_chars": 80,
    "context_window_chars": 700,
    "max_clauses_per_topic": 20,
    "max_total_clauses": 150,
    "use_llm_summarization": False,
    "cache_dir": ".cache/clauses",
    "debug": False,
}

EVIDENCE_GRADES = [
    "Reported",
    "Guided",
    "Calculated",
    "Reconstructed",
    "Proxy-based",
    "Scenario-based",
    "Unknown",
]

MODEL_LINES = [
    "revenue_growth",
    "segment_revenue_growth",
    "gross_margin",
    "opex_ratio",
    "ebit_margin",
    "nopat_margin",
    "ocf_margin",
    "maintenance_capex_pct_revenue",
    "growth_capex_pct_revenue",
    "working_capital_pct_revenue",
    "inventory",
    "receivables",
    "deferred_revenue",
    "debt",
    "net_debt",
    "wacc",
    "terminal_growth",
    "terminal_multiple",
    "diluted_shares",
    "sbc",
    "buybacks",
    "scenario_probability",
    "margin_of_safety",
]
