from __future__ import annotations

CLAUSE_TOPICS = {
    "CAPEX": [
        "capital expenditures",
        "capital expenditure",
        "capital spending",
        "property and equipment",
        "purchase of equipment",
        "purchases of property and equipment",
        "facility expansion",
        "manufacturing capacity",
        "data center",
        "infrastructure investment",
        "automation",
        "production equipment",
        "equipment purchases",
        "build-out",
        "expansion of facilities",
    ],
    "BACKLOG_RPO_BOOKINGS": [
        "backlog",
        "remaining performance obligations",
        "rpo",
        "bookings",
        "orders",
        "contracted revenue",
        "contract liabilities",
        "deferred revenue",
        "performance obligations",
        "order book",
        "pipeline",
    ],
    "REVENUE_GROWTH": [
        "revenue increased",
        "revenue decreased",
        "sales increased",
        "sales decreased",
        "growth was driven by",
        "decline was driven by",
        "volume",
        "pricing",
        "customer demand",
        "new customers",
        "retention",
        "churn",
        "usage",
        "arpu",
        "subscription revenue",
        "recurring revenue",
    ],
    "MARGIN_COSTS": [
        "gross margin",
        "operating margin",
        "cost of revenue",
        "cost of sales",
        "pricing pressure",
        "product mix",
        "sales mix",
        "higher costs",
        "lower costs",
        "sales efficiency",
        "restructuring",
        "automation",
        "labor costs",
        "cloud costs",
        "hosting costs",
        "freight",
        "input costs",
    ],
    "OCF_WORKING_CAPITAL": [
        "operating cash flow",
        "cash provided by operating activities",
        "cash used in operating activities",
        "working capital",
        "accounts receivable",
        "receivables",
        "inventory",
        "contract assets",
        "contract liabilities",
        "deferred revenue",
        "prepaid expenses",
        "accrued expenses",
        "days sales outstanding",
    ],
    "M_AND_A": [
        "acquisition",
        "acquired",
        "business combination",
        "purchase price",
        "goodwill",
        "intangible assets",
        "integration",
        "synergies",
        "impairment",
        "contingent consideration",
        "earnout",
        "divestiture",
        "disposition",
        "merger",
    ],
    "SBC_DILUTION_BUYBACKS": [
        "stock-based compensation",
        "share-based compensation",
        "rsu",
        "restricted stock",
        "options",
        "equity awards",
        "diluted shares",
        "share repurchase",
        "repurchase program",
        "buyback",
        "treasury stock",
        "anti-dilutive",
        "employee stock purchase",
    ],
    "DEBT_LIQUIDITY": [
        "liquidity",
        "debt",
        "borrowings",
        "credit facility",
        "revolving credit",
        "term loan",
        "interest expense",
        "covenants",
        "maturity",
        "cash and cash equivalents",
        "capital resources",
        "going concern",
    ],
    "GUIDANCE_OUTLOOK": [
        "guidance",
        "outlook",
        "expect",
        "expects",
        "forecast",
        "target",
        "long-term model",
        "we believe",
        "we anticipate",
        "we estimate",
        "we plan",
        "we intend",
        "future growth",
        "future revenue",
        "future margin",
    ],
    "MANAGEMENT_CREDIBILITY": [
        "strategic priorities",
        "capital allocation",
        "long-term strategy",
        "management believes",
        "management expects",
        "executive compensation",
        "performance goals",
        "incentive compensation",
        "board of directors",
        "founder",
        "chief executive officer",
        "chief financial officer",
    ],
    "MOAT_COMPETITION": [
        "competition",
        "competitive",
        "competitive advantage",
        "switching costs",
        "customer retention",
        "net retention",
        "patents",
        "intellectual property",
        "regulatory approval",
        "distribution",
        "platform",
        "ecosystem",
        "integrations",
        "scale",
        "network effects",
        "market share",
    ],
    "RISK_FACTORS": [
        "risk factors",
        "may adversely affect",
        "could adversely affect",
        "material adverse",
        "uncertainty",
        "subject to",
        "depend on",
        "reliance on",
        "concentration",
        "regulation",
        "litigation",
        "cybersecurity",
        "supply chain",
    ],
}

SUBTOPIC_RULES = {
    "CAPEX": [
        ("Maintenance CAPEX", ["maintenance", "replacement"]),
        ("Growth CAPEX", ["growth capital", "expansion", "build-out"]),
        ("Capacity Expansion", ["capacity", "facility", "data center", "manufacturing"]),
        ("Automation / Productivity Investment", ["automation", "productivity"]),
    ],
    "BACKLOG_RPO_BOOKINGS": [
        ("Backlog Increase", ["increase", "higher", "grew", "growth"]),
        ("Backlog Decline", ["decrease", "decline", "lower"]),
        ("RPO / Contracted Revenue", ["remaining performance", "rpo", "contracted revenue"]),
        ("Bookings / Orders", ["booking", "order"]),
    ],
    "REVENUE_GROWTH": [
        ("Pricing", ["pricing", "price"]),
        ("Volume", ["volume", "usage"]),
        ("New Customers", ["new customers"]),
        ("Retention / Churn", ["retention", "churn"]),
        ("Segment Growth", ["segment"]),
        ("Organic Growth", ["revenue", "sales", "growth"]),
    ],
    "MARGIN_COSTS": [
        ("Gross Margin Pressure", ["pressure", "higher costs", "lower margin"]),
        ("Gross Margin Expansion", ["margin expansion", "higher margin", "lower costs"]),
        ("OPEX Leverage", ["operating leverage", "sales efficiency"]),
        ("Restructuring", ["restructuring"]),
        ("Cost Inflation", ["inflation", "freight", "labor costs", "input costs"]),
        ("Mix Shift", ["mix"]),
    ],
    "OCF_WORKING_CAPITAL": [
        ("Receivables Risk", ["receivable", "days sales outstanding"]),
        ("Inventory Build", ["inventory"]),
        ("Deferred Revenue Support", ["deferred revenue", "contract liabilities"]),
        ("Working Capital Drag", ["working capital", "prepaid", "accrued"]),
        ("OCF Quality", ["operating cash flow", "cash provided"]),
    ],
    "M_AND_A": [
        ("Goodwill / Intangibles", ["goodwill", "intangible"]),
        ("Impairment Risk", ["impairment"]),
        ("Integration", ["integration"]),
        ("Synergies", ["synergies"]),
        ("Divestiture", ["divestiture", "disposition"]),
        ("Acquisition", ["acquisition", "acquired", "business combination"]),
    ],
    "SBC_DILUTION_BUYBACKS": [
        ("SBC", ["stock-based", "share-based"]),
        ("Dilution", ["diluted shares", "equity awards", "options", "rsu"]),
        ("Buyback Offset", ["repurchase", "buyback", "treasury stock"]),
        ("Share Count Risk", ["anti-dilutive"]),
    ],
    "DEBT_LIQUIDITY": [
        ("Debt Increase", ["debt", "borrowings", "term loan"]),
        ("Liquidity Strength", ["liquidity", "cash and cash equivalents"]),
        ("Covenant Risk", ["covenant"]),
        ("Refinancing Risk", ["maturity", "revolving credit"]),
    ],
    "GUIDANCE_OUTLOOK": [
        ("Revenue Guidance", ["future revenue", "revenue", "sales"]),
        ("Margin Guidance", ["future margin", "margin"]),
        ("CAPEX Guidance", ["capital expenditure", "capital spending"]),
        ("OCF / FCF Guidance", ["cash flow", "free cash flow"]),
        ("Long-Term Target", ["long-term", "target"]),
    ],
    "MANAGEMENT_CREDIBILITY": [
        ("Capital Allocation", ["capital allocation"]),
        ("Incentive Design", ["incentive", "compensation"]),
        ("Strategic Consistency", ["strategy", "strategic"]),
        ("Execution Claim", ["management believes", "management expects"]),
    ],
    "MOAT_COMPETITION": [
        ("Switching Costs", ["switching"]),
        ("Scale", ["scale"]),
        ("IP / Patents", ["patent", "intellectual property"]),
        ("Distribution", ["distribution"]),
        ("Regulation", ["regulatory"]),
        ("Customer Retention", ["retention"]),
        ("Pricing Power", ["pricing power"]),
    ],
    "RISK_FACTORS": [
        ("Competition Risk", ["competition", "competitive"]),
        ("Customer Concentration", ["concentration", "customer"]),
        ("Regulation", ["regulation"]),
        ("Litigation", ["litigation", "legal"]),
        ("Technology Shift", ["technology"]),
        ("Macro / FX", ["macro", "foreign exchange", "fx"]),
    ],
}


def classify_clause_topic(clause_text: str, section: str, keyword_topic: str | None = None) -> dict:
    """
    Classify a clause into topic/subtopic with rule-based confidence.
    """
    text = (clause_text or "").lower()
    topic = keyword_topic
    if not topic:
        scores = {name: sum(1 for keyword in keywords if keyword in text) for name, keywords in CLAUSE_TOPICS.items()}
        topic = max(scores, key=scores.get) if scores and max(scores.values()) else "RISK_FACTORS"
    subtopic = "General"
    reason = f"Matched {topic} language."
    for candidate, keywords in SUBTOPIC_RULES.get(topic, []):
        if any(keyword in text for keyword in keywords):
            subtopic = candidate
            reason = f"Matched {candidate} language in {section or 'filing text'}."
            break
    confidence = "High" if keyword_topic and subtopic != "General" else "Medium" if keyword_topic else "Low"
    return {"topic": topic, "subtopic": subtopic, "confidence": confidence, "reason": reason}
