from __future__ import annotations


SUPPORTED_DRIVER_PROFILES = [
    "AI Infrastructure / Data Center",
    "SaaS / Software",
    "Semiconductor",
    "Marketplace / Platform",
    "Consumer Brand",
    "Financial / Fintech",
    "Industrial / Hardware",
    "Energy / Commodity",
    "Biotech / Pharma",
    "Real Estate / REIT",
    "General",
]


AI_INFRA_DRIVER_ROWS = [
    "blackwell_gw_deployed",
    "rubin_gw_deployed",
    "other_gw_deployed",
    "utilization",
    "revenue_per_blackwell_gw",
    "revenue_per_rubin_gw",
    "revenue_per_other_gw",
    "adjusted_ebitda_margin",
    "hardware_cost_per_blackwell_gw",
    "hardware_cost_per_rubin_gw",
    "hardware_cost_per_other_gw",
    "land_power_cooling_cost_per_blackwell_gw",
    "land_power_cooling_cost_per_rubin_gw",
    "land_power_cooling_cost_per_other_gw",
    "gpu_useful_life",
    "infrastructure_useful_life",
    "maintenance_capex_pct_revenue",
    "customer_prepayment_pct",
    "equity_funding_pct",
    "equity_issue_price",
    "sbc_dilution_pct",
    "share_repurchases",
    "cost_of_debt",
    "risk_free_rate",
    "beta",
    "equity_risk_premium",
    "tax_rate",
    "exit_ebitda_multiple",
    "exit_ebit_multiple",
    "earnings_multiple",
]


DRIVER_TEMPLATES = {
    "AI Infrastructure / Data Center": {
        "profile": "AI Infrastructure / Data Center",
        "description": "Capacity, chip generation mix, utilization, revenue per GW, build cost per GW, prepayments, funding, and dilution drive valuation.",
        "driver_groups": {
            "Capacity": ["blackwell_gw_deployed", "rubin_gw_deployed", "other_gw_deployed"],
            "Unit Economics": ["revenue_per_blackwell_gw", "revenue_per_rubin_gw", "revenue_per_other_gw"],
            "Utilization": ["utilization"],
            "Margins": ["adjusted_ebitda_margin", "tax_rate"],
            "Reinvestment / CAPEX": [
                "hardware_cost_per_blackwell_gw",
                "hardware_cost_per_rubin_gw",
                "hardware_cost_per_other_gw",
                "land_power_cooling_cost_per_blackwell_gw",
                "land_power_cooling_cost_per_rubin_gw",
                "land_power_cooling_cost_per_other_gw",
                "maintenance_capex_pct_revenue",
            ],
            "Depreciation": ["gpu_useful_life", "infrastructure_useful_life"],
            "Funding": ["customer_prepayment_pct", "equity_funding_pct", "cost_of_debt"],
            "Dilution": ["equity_issue_price", "sbc_dilution_pct", "share_repurchases"],
            "Valuation": ["risk_free_rate", "beta", "equity_risk_premium", "exit_ebitda_multiple", "exit_ebit_multiple", "earnings_multiple"],
        },
        "derived_financial_lines": [
            "Total energized GW",
            "Average total GW",
            "Revenue",
            "Adjusted EBITDA",
            "Hardware depreciation",
            "EBIT",
            "NOPAT",
            "Operating cash flow",
            "Growth CAPEX",
            "Total CAPEX",
            "Free cash flow",
            "Ending net debt",
            "Shares outstanding",
        ],
        "default_driver_assumptions": {
            "blackwell_gw_deployed": 0.0,
            "rubin_gw_deployed": 0.0,
            "other_gw_deployed": 0.2,
            "utilization": 0.70,
            "revenue_per_blackwell_gw": 1_500_000_000.0,
            "revenue_per_rubin_gw": 1_800_000_000.0,
            "revenue_per_other_gw": 1_000_000_000.0,
            "adjusted_ebitda_margin": 0.35,
            "hardware_cost_per_blackwell_gw": 1_000_000_000.0,
            "hardware_cost_per_rubin_gw": 1_150_000_000.0,
            "hardware_cost_per_other_gw": 800_000_000.0,
            "land_power_cooling_cost_per_blackwell_gw": 650_000_000.0,
            "land_power_cooling_cost_per_rubin_gw": 700_000_000.0,
            "land_power_cooling_cost_per_other_gw": 450_000_000.0,
            "gpu_useful_life": 5.0,
            "infrastructure_useful_life": 15.0,
            "maintenance_capex_pct_revenue": 0.03,
            "customer_prepayment_pct": 0.10,
            "equity_funding_pct": 0.10,
            "sbc_dilution_pct": 0.02,
            "cost_of_debt": 0.08,
            "risk_free_rate": 0.04,
            "beta": 1.4,
            "equity_risk_premium": 0.055,
            "tax_rate": 0.21,
            "exit_ebitda_multiple": 12.0,
            "exit_ebit_multiple": 16.0,
            "earnings_multiple": 25.0,
        },
        "scenario_rules": {
            "Bear Case": {"capacity": 0.75, "unit_economics": 0.85, "margin_delta": -0.05, "capex": 1.15},
            "Base Case": {"capacity": 1.00, "unit_economics": 1.00, "margin_delta": 0.00, "capex": 1.00},
            "Bull Case": {"capacity": 1.25, "unit_economics": 1.15, "margin_delta": 0.05, "capex": 0.90},
        },
    },
    "SaaS / Software": {
        "profile": "SaaS / Software",
        "description": "ARR/revenue, customer growth, net retention, churn, ARPU, gross margin, sales efficiency, R&D, SBC, OCF, and CAPEX intensity.",
        "driver_groups": {"Growth": ["capacity_added", "revenue_per_unit"], "Margins": ["ebitda_margin"], "Capital": ["maintenance_cost_per_unit"]},
        "derived_financial_lines": ["Revenue", "EBITDA", "OCF", "FCF"],
        "default_driver_assumptions": {},
        "scenario_rules": {},
    },
    "Semiconductor": {
        "profile": "Semiconductor",
        "description": "Units shipped, ASP, production capacity, utilization, gross margin, R&D intensity, inventory cycle, CAPEX intensity, and pricing cycle.",
        "driver_groups": {"Volume": ["capacity_added", "utilization"], "Pricing": ["revenue_per_unit"], "Capital": ["hardware_cost_per_unit"]},
        "derived_financial_lines": ["Revenue", "EBIT", "OCF", "CAPEX", "FCF"],
        "default_driver_assumptions": {},
        "scenario_rules": {},
    },
    "Marketplace / Platform": {
        "profile": "Marketplace / Platform",
        "description": "GMV, take rate, active users, transactions per user, gross margin, trust/safety cost, OCF margin, and CAPEX intensity.",
        "driver_groups": {"Activity": ["capacity_added"], "Take Rate": ["revenue_per_unit"], "Margins": ["ebitda_margin"]},
        "derived_financial_lines": ["Revenue", "EBITDA", "OCF", "FCF"],
        "default_driver_assumptions": {},
        "scenario_rules": {},
    },
    "Consumer Brand": {
        "profile": "Consumer Brand",
        "description": "Units sold, ASP, channel growth, gross margin, marketing intensity, inventory, and store count when relevant.",
        "driver_groups": {"Volume": ["capacity_added"], "Pricing": ["revenue_per_unit"], "Margins": ["ebitda_margin"]},
        "derived_financial_lines": ["Revenue", "EBIT", "OCF", "FCF"],
        "default_driver_assumptions": {},
        "scenario_rules": {},
    },
    "Financial / Fintech": {
        "profile": "Financial / Fintech",
        "description": "AUM/deposits/loan book, net interest margin, fee rate, credit losses, capital ratio, expense ratio, ROE, and book value growth.",
        "driver_groups": {"Assets": ["capacity_added"], "Yield": ["revenue_per_unit"], "Profitability": ["ebitda_margin"]},
        "derived_financial_lines": ["Revenue", "NOPAT", "ROE proxy", "Fair value"],
        "default_driver_assumptions": {},
        "scenario_rules": {},
    },
    "Industrial / Hardware": {
        "profile": "Industrial / Hardware",
        "description": "Units, ASP, capacity utilization, production cost, gross margin, R&D/OPEX, working capital, and CAPEX intensity.",
        "driver_groups": {"Capacity": ["capacity_added", "utilization"], "Unit Economics": ["revenue_per_unit"], "Capital": ["hardware_cost_per_unit"]},
        "derived_financial_lines": ["Revenue", "EBIT", "OCF", "CAPEX", "FCF"],
        "default_driver_assumptions": {},
        "scenario_rules": {},
    },
    "Energy / Commodity": {
        "profile": "Energy / Commodity",
        "description": "Production volume, realized price, lifting/operating cost, decline rates, reserves, maintenance CAPEX, and commodity cycle.",
        "driver_groups": {"Production": ["capacity_added"], "Pricing": ["revenue_per_unit"], "Capital": ["hardware_cost_per_unit"]},
        "derived_financial_lines": ["Revenue", "EBITDA", "OCF", "CAPEX", "FCF"],
        "default_driver_assumptions": {},
        "scenario_rules": {},
    },
    "Biotech / Pharma": {
        "profile": "Biotech / Pharma",
        "description": "Pipeline stage, approval probability, launch timing, peak sales, royalty/COGS, R&D burn, dilution, and cash runway.",
        "driver_groups": {"Pipeline": ["capacity_added"], "Peak Sales": ["revenue_per_unit"], "Funding": ["equity_funding_pct"]},
        "derived_financial_lines": ["Revenue", "R&D burn", "Cash runway", "Dilution"],
        "default_driver_assumptions": {},
        "scenario_rules": {},
    },
    "Real Estate / REIT": {
        "profile": "Real Estate / REIT",
        "description": "Square footage/properties, occupancy, rent per unit, NOI margin, cap rate, debt cost, maintenance CAPEX, and AFFO.",
        "driver_groups": {"Properties": ["capacity_added", "utilization"], "Rent": ["revenue_per_unit"], "Debt": ["cost_of_debt"]},
        "derived_financial_lines": ["Revenue", "NOI proxy", "AFFO proxy", "Net debt"],
        "default_driver_assumptions": {},
        "scenario_rules": {},
    },
    "General": {
        "profile": "General",
        "description": "Fallback generic DCF drivers: revenue growth, margins, CAPEX, working capital, WACC, terminal growth, terminal multiple, and shares.",
        "driver_groups": {"Generic DCF": ["revenue_cagr", "gross_margin", "opex_pct_revenue", "wacc"]},
        "derived_financial_lines": ["Revenue", "NOPAT", "OCF", "FCF", "Fair value"],
        "default_driver_assumptions": {},
        "scenario_rules": {},
    },
}


def driver_profile_options() -> list[str]:
    return list(SUPPORTED_DRIVER_PROFILES)


def get_driver_template(profile: str) -> dict:
    return DRIVER_TEMPLATES.get(profile, DRIVER_TEMPLATES["General"])
